# Global --------------------------

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - quality
  - tests

# Jobs templates ------------------

.install-deps-template: &install-deps
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
    # Install Go for pre-commit hook (shfmt)
    - >
      GO_TAR=go1.15.linux-amd64.tar.gz &&
      wget --quiet https://golang.org/dl/$GO_TAR &&
      tar -C /usr/local -xzf $GO_TAR &&
      rm $GO_TAR &&
      export GO111MODULE=on &&
      export CGO_ENABLED=0 &&
      export GOOS=linux &&
      export GOARCH=amd64 &&
      export PATH="${PATH}:/usr/local/go/bin"

.quality-template: &quality
  <<: *install-deps
  image: python:3.7
  stage: quality

.test-template: &test
  <<: *install-deps
  stage: tests
  coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
  script: make test
  artifacts:
    paths:
      - tests/logs
    when: always
    expire_in: 1 week

# Quality jobs ----------------------

static_analysis:
  <<: *quality
  script: make lint

# Tests jobs ------------------------

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8

python3.9:
  <<: *test
  image: python:3.9
