---

include:
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    ref: master
    file:
      - '/.gitlab/ci/stages/globals.yml'
      - '/.gitlab/ci/stages/pull_docker_image/jobs/pull.yml'
      - '/.gitlab/ci/stages/sast/jobs/scan-dependencies.yml'
      - '/.gitlab/ci/stages/sast_and_code_quality/jobs/semgrep-python.yml'
      - '/.gitlab/ci/stages/code_quality/jobs/pre-commit-hooks.yml'
      - '/.gitlab/ci/stages/test/jobs/python/all.yml'

stages:
  - Pull Docker Image
  - SAST
  - SAST & Code Quality
  - Code Quality
  - Test

variables:
  # For `pre-commit-hooks` job
  SKIP: cruft
