---
# Needed because Dependabot-initiated pushes to master do not have access
# to repository secrets on which downstream workflows rely.
# see: dependabot/dependabot-core/issues/3253
name: Dependabot PR Check

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    # yamllint disable-line rule:braces
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
